/**
 * Curated pool of common 5-letter English words used as Wordle Race secrets.
 * Lowercase, singular nouns/adjectives/verbs — no plurals-with-s, no
 * profanity. Not a dictionary of valid guesses; the game accepts any
 * 5-letter guess (see wordle.ts validateMove).
 */
export const ANSWERS: string[] = [
  "crane", "slate", "pride", "adieu", "audio", "roate", "arise", "irate",
  "stare", "raise", "arose", "trace", "least", "alter", "later", "learn",
  "plant", "grant", "board", "beach", "brave", "bread", "break", "bring",
  "brown", "brush", "build", "buyer", "candy", "carry", "catch", "cause",
  "chair", "chalk", "charm", "chase", "cheap", "check", "chest", "chief",
  "child", "china", "chord", "cider", "civic", "claim", "class", "clean",
  "clear", "climb", "cling", "clock", "close", "cloth", "cloud", "clown",
  "coach", "coast", "color", "count", "court", "cover", "craft", "crash",
  "crazy", "cream", "creek", "crest", "crisp", "cross", "crowd", "crown",
  "crush", "curve", "cycle", "daily", "dance", "delay", "depth", "diary",
  "dodge", "dozen", "draft", "drain", "drama", "dream", "dress", "drift",
  "drink", "drive", "dryer", "eager", "eagle", "early", "earth", "elbow",
  "elder", "elite", "empty", "enter", "entry", "equal", "error", "event",
  "every", "exact", "exist", "extra", "fable", "faith", "false", "fault",
  "favor", "feast", "fence", "fiber", "field", "fifth", "fifty", "fight",
  "final", "first", "flame", "flash", "fleet", "flesh", "flint", "float",
  "flock", "flood", "floor", "flour", "fluid", "focus", "force", "forge",
  "forth", "forty", "forum", "found", "frame", "fresh", "front", "frost",
  "fruit", "funny", "gauge", "ghost", "giant", "given", "glass", "globe",
  "glory", "glove", "grace", "grade", "grain", "grand", "grape", "graph",
  "grass", "great", "green", "greet", "grief", "grill", "grind", "groom",
  "gross", "group", "grove", "grown", "guard", "guess", "guest", "guide",
  "habit", "happy", "harsh", "haste", "haven", "heart", "heavy", "hedge",
  "hello", "hence", "honey", "honor", "horse", "hotel", "house", "human",
  "humor", "hurry", "ideal", "image", "index", "inner", "input", "issue",
  "ivory", "jelly", "joint", "judge", "juice", "known", "label", "labor",
  "large", "laser", "laugh", "layer", "level", "light", "limit", "liver",
  "lobby", "local", "lodge", "logic", "loose", "lower", "loyal", "lucky",
  "lunar", "lunch", "magic", "major", "maker", "march", "match", "maybe",
  "mayor", "medal", "media", "metal", "meter", "might", "minor", "minus",
  "mixed", "model", "money", "month", "moral", "motor", "mount", "mouse",
  "mouth", "movie", "music", "naive", "never", "newly", "night", "noble",
  "noise", "north", "novel", "nurse", "occur", "ocean", "offer", "often",
  "olive", "onion", "opera", "orbit", "order", "organ", "other", "outer",
  "owner", "paint", "panel", "panic", "paper", "party", "pause", "peace",
  "phase", "phone", "photo", "piano", "piece", "pilot", "pitch", "pizza",
  "place", "plain", "plane", "plate", "point", "pound", "power", "press",
  "price", "print", "prize", "proof", "proud", "prove", "pulse", "punch",
  "pupil", "purse", "queen", "query", "quick", "quiet", "quilt", "quote",
  "radio", "rally", "ranch", "range", "rapid", "ratio", "reach", "rider",
  "ready", "realm", "rebel", "refer", "reign", "relax", "reply", "resin",
  "rival", "river", "roast", "robin", "robot", "rocky", "rough", "round",
  "route", "royal", "rugby", "rural", "salad", "salon", "sauce", "scale",
  "scarf", "scene", "scent", "scope", "score", "scout", "screw", "sense",
  "serve", "seven", "shade", "shake", "shall", "shame", "shape", "share",
  "shark", "sharp", "sheep", "sheet", "shelf", "shell", "shine", "shirt",
  "shock", "shoot", "shore", "short", "shout", "shown", "sight", "silly",
  "since", "sixth", "sixty", "skill", "skirt", "sleep", "slice", "slide",
  "slope", "small", "smart", "smell", "smile", "smoke", "snack", "solar",
  "solid", "solve", "sorry", "sound", "south", "space", "spare", "spark",
  "speak", "speed", "spend", "spice", "spine", "spoil", "split", "sport",
  "spray", "squad", "stack", "staff", "stage", "stain", "stamp", "stand",
  "start", "state", "steak", "steam", "steel", "steep", "steer", "stick",
  "still", "stock", "stone", "store", "storm", "story", "stove", "study",
  "stuff", "style", "sugar", "suite", "sunny", "super", "sweet", "swift",
  "swing", "sword", "table", "taste", "teach", "tempo", "tenth", "theme",
  "there", "thick", "thing", "think", "third", "throw", "thumb", "tiger",
  "tight", "timer", "tired", "title", "toast", "today", "token", "tooth",
  "topic", "torch", "total", "touch", "tough", "tower", "toxic", "trade",
  "trail", "train", "treat", "trend", "trial", "tribe", "trick", "troop",
  "truck", "truly", "trunk", "trust", "truth", "tulip", "tutor", "twice",
  "twist", "ultra", "uncle", "under", "union", "unite", "unity", "until",
  "upper", "urban", "usage", "usual", "valid", "value", "vapor", "vault",
  "vegan", "venue", "video", "villa", "vinyl", "viral", "virus", "visit",
  "vital", "vivid", "vocal", "voice", "waste", "watch", "water", "weigh",
  "weird", "wheat", "wheel", "where", "which", "while", "white", "whole",
  "whose", "widen", "widow", "width", "windy", "wafer", "witch", "woman",
  "world", "worry", "worth", "wound", "woven", "wrist", "write", "wrong",
  "yield", "young", "youth", "zebra",
];
